#!/bin/bash
#SBATCH --job-name=treemnl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=72:00:00
#SBATCH --mem=20GB
#SBATCH --array=25,47,69
#SBATCH --output=/home/xz2197/out/qr_%A_%a.out
#SBATCH --error=/home/xz2197/err/qr_%A_%a.err

module purge
module load matlab/2017b
module load knitro/12.1.0

cd /home/xz2197

srun matlab -nosplash -nodesktop -nodisplay -r "run_scenarios($SLURM_ARRAY_TASK_ID)"