#!/bin/bash
#SBATCH --job-name=treemnl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=50:00:00
#SBATCH --mem=40GB
#SBATCH --array=1-5
#SBATCH --output=/scratch/av1196/NestedLogitEstimation/out/qr_%A_%a.out
#SBATCH --error=/scratch/av1196/NestedLogitEstimation/err/qr_%A_%a.err

module purge
module load matlab/2020b
module load knitro/12.3.0

cd /scratch/av1196/NestedLogitEstimation

srun matlab -nosplash -nodesktop -nodisplay -r "run_scenarios($SLURM_ARRAY_TASK_ID)"
