#!/bin/bash
#SBATCH --job-name=sushi-nl
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH --mem=20GB
#SBATCH --array=1-10
#SBATCH --output=/scratch/av1196/NestedLogitEstimation/out/sushi_nl_%a.out
#SBATCH --error=/scratch/av1196/NestedLogitEstimation/err/sushi_nl_%a.err

module purge
module load matlab/2020b
module load knitro/12.3.0

cd /scratch/av1196/NestedLogitEstimation/sushi_code

srun matlab -nosplash -nodesktop -nodisplay -r "Training_final_NL($SLURM_ARRAY_TASK_ID, false)"
